Feature: Standard exceptions are generated

  Background:
    Given Directory structure with namespaces
    And Application with current path "project/src/Foo/Bar/My"
    And option for disabling parent exception search is "set"
    And dummy files and folders in all directories

  Scenario: exceptions are generated by a namespace found in a php file
    Given a path containing php classes with namespaces in same path
    When the application is executed
    Then a file named "BadMethodCallException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use BadMethodCallException as BaseBadMethodCallException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class BadMethodCallException extends BaseBadMethodCallException implements ExceptionInterface
    {
    }

    """
    And a file named "DomainException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use DomainException as BaseDomainException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class DomainException extends BaseDomainException implements ExceptionInterface
    {
    }

    """
    And a file named "InvalidArgumentException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use InvalidArgumentException as BaseInvalidArgumentException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class InvalidArgumentException extends BaseInvalidArgumentException implements ExceptionInterface
    {
    }

    """
    And a file named "LengthException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use LengthException as BaseLengthException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class LengthException extends BaseLengthException implements ExceptionInterface
    {
    }

    """
    And a file named "LogicException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use LogicException as BaseLogicException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class LogicException extends BaseLogicException implements ExceptionInterface
    {
    }

    """
    And a file named "OutOfBoundsException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use OutOfBoundsException as BaseOutOfBoundsException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class OutOfBoundsException extends BaseOutOfBoundsException implements ExceptionInterface
    {
    }

    """
    And a file named "OverflowException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use OverflowException as BaseOverflowException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class OverflowException extends BaseOverflowException implements ExceptionInterface
    {
    }

    """
    And a file named "RangeException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use RangeException as BaseRangeException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class RangeException extends BaseRangeException implements ExceptionInterface
    {
    }

    """
    And a file named "RuntimeException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use RuntimeException as BaseRuntimeException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class RuntimeException extends BaseRuntimeException implements ExceptionInterface
    {
    }

    """
    And a file named "UnderflowException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use UnderflowException as BaseUnderflowException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class UnderflowException extends BaseUnderflowException implements ExceptionInterface
    {
    }

    """
    And a file named "UnexpectedValueException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use UnexpectedValueException as BaseUnexpectedValueException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class UnexpectedValueException extends BaseUnexpectedValueException implements ExceptionInterface
    {
    }

    """
    And a file named "ExceptionInterface.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    interface ExceptionInterface
    {
    }

    """

  Scenario: exceptions are generated by a namespace found in a php file
    Given a path containing php classes with namespaces
    When the application is executed
    Then a file named "BadMethodCallException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use BadMethodCallException as BaseBadMethodCallException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class BadMethodCallException extends BaseBadMethodCallException implements ExceptionInterface
    {
    }

    """

  Scenario: exceptions are generated by a psr-4 namespace found in composer.json
    Given a path containing a composer.json with a "psr-4" namespace
    When the application is executed
    Then a file named "BadMethodCallException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use BadMethodCallException as BaseBadMethodCallException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class BadMethodCallException extends BaseBadMethodCallException implements ExceptionInterface
    {
    }

    """

  Scenario: exceptions are generated by a psr-4 namespace found in composer.json
    Given a path containing a composer.json with a "psr-0" namespace
    When the application is executed
    Then a file named "BadMethodCallException.php" should be created in "/project/src/Foo/Bar/My/Exception/" with content
    """
    <?php
    namespace Foo\Bar\My\Exception;

    use BadMethodCallException as BaseBadMethodCallException;

    /**
     * Generated at %s, %d %s %d %d:%d:%d +0000 by behat
     */
    class BadMethodCallException extends BaseBadMethodCallException implements ExceptionInterface
    {
    }

    """
