<?php
namespace Burntromi\ExceptionGenerator\Generator;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-05 at 17:00:57.
 */
class ExceptionClassNamesTest extends TestCase
{
    /**
     * @var ExceptionClassNames
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExceptionClassNames;
    }

    /**
     * @covers Burntromi\ExceptionGenerator\Generator\ExceptionClassNames::getExceptionClassNames
     */
    public function testGetExceptionClassNames()
    {
        $this->assertSame(
            array(
                'BadMethodCallException',
                'DomainException',
                'InvalidArgumentException',
                'LengthException',
                'LogicException',
                'OutOfBoundsException',
                'OutOfRangeException',
                'OverflowException',
                'RangeException',
                'RuntimeException',
                'UnderflowException',
                'UnexpectedValueException'
            ),
            $this->object->getExceptionClassNames()
        );
    }
}
